#version: '3,5'
#services:
#  postgres:
#    container_name: postgres
#    restart: always
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_USER=admin
#    image: postgres:14.7-alpine
#    volumes:
#      - postgres:/var/lib/postgresql/data
#volumes:
#  postgres:
version: '3.5'

services:
  postgres:
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    image: postgres:14.7-alpine
